import os

LOG_LEVEL = "INFO"

# Version in the Consul path for all services
CONSUL_CONFIG_VERSION = "2.0"

# API Version
API_VERSION = "v2"

# Deploy type: docker, manual
DEPLOY_TYPE = "docker"
SERVICE_STARTUP_RECHECK_TIMES = 5
SERVICE_STARTUP_WAIT_TIME = 3

# EdgeX host
BASE_URL = "localhost"

# Service port
APP_HTTP_EXPORT_PORT = 48101
APP_MQTT_EXPORT_PORT = 48103
APP_FUNCTIOAL_TESTS_PORT = 48105
SYS_MGMT_AGENT_PORT = 48090
REGISTRY_PORT = 8500
jwt_token = ''
consul_token = ''
SECURITY_SERVICE_NEEDED=os.getenv("SECURITY_SERVICE_NEEDED")
if SECURITY_SERVICE_NEEDED == 'true':
    URI_SCHEME = "https"
    CORE_DATA_PORT = "8443/coredata"
    CORE_METADATA_PORT = "8443/metadata"
    CORE_COMMAND_PORT = "8443/command"
    SUPPORT_LOGGING_PORT = "8443/logging"
    SUPPORT_NOTIFICATION_PORT = "8443/notifications"
    SUPPORT_SCHEDULER_PORT = "8443/scheduler"
    SUPPORT_RULESENGINE_PORT = "8443/rulesengine"
else:
    URI_SCHEME = "http"
    CORE_DATA_PORT = 48080
    CORE_METADATA_PORT = 48081
    CORE_COMMAND_PORT = 48082
    SUPPORT_LOGGING_PORT = 48061
    SUPPORT_NOTIFICATION_PORT = 48060
    SUPPORT_SCHEDULER_PORT = 48085
    SUPPORT_RULESENGINE_PORT = 48075

