import os

LOG_LEVEL = "INFO"

# Deploy type: docker, manual
DEPLOY_TYPE = "docker"
SERVICE_STARTUP_RECHECK_TIMES = 5
SERVICE_STARTUP_WAIT_TIME = 3

# EdgeX host
BASE_URL = "localhost"

# Service port
APP_SERVICE_HTTP_EXPORT_PORT = 48096
APP_SERVICE_MQTT_EXPORT_PORT = 48097
REGISTRY_PORT = 8500
jwt_token=''
SECURITY_SERVICE_NEEDED=os.getenv("SECURITY_SERVICE_NEEDED")
URI_SCHEME = "http"
CORE_DATA_PORT = 48080
CORE_METADATA_PORT = 48081
CORE_COMMAND_PORT = 48082
SUPPORT_LOGGING_PORT = 48061
SUPPORT_NOTIFICATION_PORT = 48060
SUPPORT_SCHEDULER_PORT = 48085
SUPPORT_RULESENGINE_PORT = 48075

